blank_issues_enabled: false
contact_links:
  - name: Deepgram Developer Community
    url: https://github.com/orgs/infinitusai/discussions
  - name: Deepgram on Twitter
    url: https://twitter.com/DeepgramAI
